### PR TITLE
Run Peloton using Docker

### PR DESCRIPTION
**Pull request by rishiloyola**
This pull request contains Dockerfile of Peloton. One can easily build their own image using this docker file.

**Steps :**

- Make sure you have installed Docker on your machine.
```
docker build -t <name of your image> .
```
- After docker successfully builds this image you can create containers of this image and can run it in the background.
```
docker run -d --name <name of your container>  <name of your image>
```

### CODE REVIEW

**Comment by jarulraj** [comment]
This looks good. But, we might want to move this to `script` directory -- like `script/docker/ubuntu-precise-amd64/Dockerfile`, so that we can add more Dockerfiles for other systems.

**Comment by rishiloyola** [comment]
I put it under the `script/docker/ubuntu-precise-amd64/` folder.
You can merge now.

**Comment by jarulraj** [comment]
Sounds good, that should work.

**Comment by rishiloyola** [comment]
@jarulraj Can I update the wiki page to install the peloton with docker?

**Pull request merged**
