### PR TITLE
Remove unnecessary null pointer checks #523

### PR DESCRIPTION
**Pull request by lixupeng**
The unnecessary null pointer checks mainly exist in include/parser. I just simply removed those if-statements.

### CODE REVIEW

**Comment by seojungmin** [comment]
This is good. I wonder whether we could use smart pointers here, more specifically unique pointers, even to get rid of delete's too.

**Comment by apavlo** [comment]
@lixupeng - @seojungmin is correct here. You should switch these to use smart pointers.

**Comment by lixupeng** [comment]
Yes, I'm trying to switch all pointers used in parser to smart pointers. But it occurs a number of compiling errors need to be fixed. I will fix them later. Further, SelectStatement is incomplete so SelectStatement* cannot be replaced by unique_ptr<SelectStatement>.

**Comment by pmenon** [comment]
@lixupeng This is because your first loop is trying to make a copy of a unique_ptr, which is not allowed by definition. You should iterate using a reference to elements, like so:

```
vector<unique_ptr<T>> vec;
for (auto &item : vec) ... 
```

Or, if you don't intend to modify the elements:

`for (const auto &item : vec) ... `

**Comment by lixupeng** [comment]
@pmenon Yeah, your solution is cool, much prettier than mine. And how about those situations that a function should recieve a pointer as argument but we have unique_ptr now?  We should use unique_ptr.get() or modify the definition of that function to receive a unique_ptr& recursively?

**Pull request closed without merging**
