### PR TITLE
Index IntsKey Fixes

### PR DESCRIPTION
**Pull request by apavlo**
This PR re-enables the specialized IntsKey comparators that were commented out for the indexes. I have not tested whether this is fully working but I added a basic test case.

I also fixed it so that we don't hardcode the name of **every** to be `CUSTOMER_PKEY` ☹

This is for #431

### CODE REVIEW

**Comment by wangziqi2013** [comment]
We called GetTupleForComparison() only in Scan(). This function has not yet been implemented yet. However it should just return the pointer passed to it in SetFromKey()

**Comment by apavlo** [comment]
@wangziqi2013 Not sure what you mean that it this function return the pointer from `SetFromKey()`? That would mean we are storing the pointer to the tuple and not the compact form of the key.

**Comment by wangziqi2013** [comment]
@apavlo I mean if we re-construct IntsKey then it should return exactly the same tuple as what is used as the argument of SetFromKey(). Right now we call SetFromKey() in InsertEntry() and DeleteEntry().

**Comment by apavlo** [comment]
@wangziqi2013 Yes, I am working on this. IntsKey's memory boundaries don't match with GenericKey. I am fixing IndexFactory.

**Comment by apavlo** [comment]
I am here with @wangziqi2013 + @Michael-Tieying-Zhang + @malin1993ml. They all agree this should be merged. So in it goes!

**Pull request merged**
