### PR TITLE
Reorganize codegen source directory

### PR DESCRIPTION
**Pull request by apavlo**
I reorganized the 'codegen' directory to move categories of classes into sub-dirs:

* `codegen/proxy`
* `codegen/operator`
* `codegen/expression`

I also renamed `codegen/utils` to `codegen/util` to match the other directory names in the repository. This is for #690.

https://www.youtube.com/watch?v=7eKv4BEujFU

### CODE REVIEW

**Comment by apavlo** [comment]
@pmenon @seojungmin I am going to rebase and then merge this today.

**Comment by seojungmin** [comment]
@apavlo The changes look good to me.  #697 is a huge PR which is almost done, and I am not sure which should go in first.  We should minimize our efforts.

**Comment by apavlo** [comment]
@seojungmin #697 should probably go first. I should then probably just redo the reorganization by hand after it is merged and send a new PR.

**Comment by pmenon** [comment]
This looks good! Once #697 goes in, rebase against it. I also think the `If` and `Loop` classes should go into a `peloton::codegen::lang` namespace. I plan on adding type wrappers around LLVM to simplify pointer addressing, numeric addition etc. and these will also fall into the `lang` namespace.

Also, this name mangling business is ugly. I need to devise a better way to handle it.

**Comment by apavlo** [comment]
Too many conflicts. Going to start over.

**Pull request closed without merging**
