### PR TITLE
Standardize macro names

### PR DESCRIPTION
**Pull request by zhaoguoquan94**
Standardize Peloton's macro names mentioned in #1019 
Also, I removed one line which caused my test failure. (cost_test.cpp:45:11: error: unused variable 'N_ROW' [-Werror,-Wunused-const-variable], MacOS).
https://github.com/cmu-db/peloton/blob/aaaa62151fc2023e570998d2df00d4ba11d85081/test/optimizer/cost_test.cpp#L45

### CODE REVIEW

**Comment by apavlo** [comment]
@zhaoguoquan94 Can you resolve the conflicts after the merge? You may want to just apply your changes again manually.

**Comment by zhaoguoquan94** [comment]
@apavlo  Done.

**Comment by pervazea** [comment]
Ping. Can you make the adjustments requested? Thanks.

**Comment by pervazea** [comment]
Ping. Small changes still to be made, as per review.

**Comment by pervazea** [comment]
No progress, closing. Issue created to pick this up and complete

**Pull request closed without merging**
