### PR TITLE
Fix for Issue 711

### PR DESCRIPTION
**Pull request by grkamat**
CREATE INSERT DELETE and UPDATE matches postgres output

### CODE REVIEW

**Comment by apavlo** [comment]
@grkamat Your reference output file ('script/testing/psql/psql_ref_out.txt') is wrong. Here is the correct version. Please add it to your PR.
[psql_ref_out.txt](https://github.com/cmu-db/peloton/files/1136440/psql_ref_out.txt)

**Comment by grkamat** [comment]
@apavlo I have updated the psql_ref_out.txt file. Sorry for the trouble.

**Comment by apavlo** [comment]
@grkamat Check the file that you committed. You removed out the last line of the output. That's why the tests are failing. I fixed it for you.

**Comment by grkamat** [comment]
@apavlo Thank you. I am sorry I didn't realize.

**Pull request merged**
