### PR TITLE
Tearing down SimpleOptimizer

### PR DESCRIPTION
**Pull request by chenboy**
This PR add support for SQL case and fully switch to new optimizer. The NEW_OPTIMIZER flag in tcop is kept for potential need for using SimpleOptimizer.

### CODE REVIEW

**Comment by apavlo** [comment]
@chenboy This is great! You have a bunch of duplicate commits from the master branch though.

**Comment by chenboy** [comment]
I already remove the duplicate commits. I believe the current drop in coverage is caused by switching to new optimizer in all the tests.

**Comment by apavlo** [comment]
@PauloAmora Can you quickly TPC-C with OLTP-Bench on this PR just to make sure that we can still run the benchmark? If that works, then I will merge this.

**Comment by PauloAmora** [comment]
Sure, but is it rebased? @AngLi-Leon and I found a bug today that happens on insert and stop us from running TPC-C. It is an easy fix, but we were hoping to bring it up tomorrow to get some input.

**Comment by apavlo** [comment]
@PauloAmora Ok we can hold off on merging this. Remind me to discuss it at the team meeting tomorrow.

**Comment by PauloAmora** [comment]
I can get the PR and edit the bug out just for testing too.

**Comment by PauloAmora** [comment]
@apavlo TPC-C looks ok, I just executed it. This may be good to go.

**Pull request merged**
