### PR TITLE
Modify StatsStorage::GetTableStats() to take a txn as a parameter instead creating a new one

### PR DESCRIPTION
**Pull request by chenboy**
As @poojanilangekar and @yingjunwu mentioned in previous emails, when visiting `ColumnStatsCatalog`, the stats storage use a `concurrency::TransactionContext*`  passed in as a parameter instead of creating a new one. This is a quick fix for that.

### CODE REVIEW

**Comment by pervazea** [comment]
This PR was a result of investigating excess transaction in #1154

**Comment by mengranwo** [comment]
@poojanilangekar @yingjunwu 
Hi guys,
Can you take a look at this PR, it seems like a quick fix(100 lines modified in total)
If nothing is wrong, please change the tag into **"accept"**

Thanks!

**Comment by yingjunwu** [comment]
looks good to me. but I was wondering why the previous version creates so many transactions? The major update in this PR is to pass in transaction manager pointer. But I am not sure why it fixes the transaction creation bug.

**Comment by yingjunwu** [comment]
build failed. please fix it.

**Comment by chenboy** [comment]
Jenkins seems to be failing for all PR now. I think it’s caused by another issue in optimizer_rule_test. This PR builds on Travis so I think it should be good.

**Comment by yingjunwu** [comment]
okay. I wonder whether you could answer the following question: `looks good to me. but I was wondering why the previous version creates so many transactions? The major update in this PR is to pass in transaction manager pointer. But I am not sure why it fixes the transaction creation bug.`

**Comment by chenboy** [comment]
As @poojanilangekar  mentioned in an earlier email, the previous version would create (and commit) a txn in `StatsStorage::GetTableStats()` because it needs to access `ColumnStatsCatalog`. This function may be called multiple times in the optimizer so we may create multiple transactions. Now we pass in the current transaction and do not create a txn each time the function is called, so it could hopefully solve the issue. I'm not sure if this is the answer you're looking for.

**Comment by yingjunwu** [comment]
okay the PR is ready to go.

**Comment by mengranwo** [comment]
@pervazea
Hi Pervaze, can you help merge in this PR? both @yingjunwu and @poojanilangekar has confirmed that it is ready to go!

Thanks!

**Comment by apavlo** [comment]
@mengranwo I will give you permissions.

**Comment by ChTimTsubasa** [comment]
@chenboy Do you also want to change the begin txn here?
https://github.com/cmu-db/peloton/blob/master/src/optimizer/stats/stats_storage.cpp#L47

**Comment by chenboy** [comment]
This function should only be called when the system initializes, so I think its fine here. But right now we do not initialize the singleton `StatsStorage` so it may cause the first query that requires stats to initialize `StatsStorage`, and thus create another txn. @poojanilangekar @yingjunwu are you currently blocked by this? If not, the cost model team will work on this in the near future, we can merge this PR first.

**Pull request merged**
