### PR TITLE
Add statistics counter to record memory usage

### PR DESCRIPTION
**Pull request by wangziqi2013**
Currently the counter is a shared member variable. Use GetMemAlloc() to obtain aggregated number of bytes allocated for Inner, Leaf and Delta nodes.

### CODE REVIEW

**Comment by wangziqi2013** [comment]
OK, I need to think more on this.

@mengranwo Do you need a statistics counter per-instance, or just a global counter for all BwTree? I ask because these two require quite different implementations

**Comment by eribeiro** [comment]
Hi @wangziqi2013, 

Does it make sense to add a method to reset or decrement the counter?

**Comment by ChTimTsubasa** [comment]
We can keep this PR as a reference for me to do memory stats without merging it.
@malin1993ml I have added some code to do memory metric stats in backend_stats_context.

**Comment by malin1993ml** [comment]
@ChTimTsubasa Are you saying that you're going to implement the feature in this PR in your own branch, so we can just close this one? You can still see the code even if we close it.

**Comment by ChTimTsubasa** [comment]
@malin1993ml Sure.

**Pull request closed without merging**
