### PR TITLE
Fixed up installation scripts

### PR DESCRIPTION
**Pull request by apavlo**
We now have a single script to install packages.
I also removed the old 'dependencies.py' file that I don't think is called anywhere (nor did it actually do anything).

### CODE REVIEW

**Comment by apavlo** [comment]
We have no way to test this quickly for now since we don't have a redhat/fedora machine, but it works fine on Ubuntu.

@SLMT Can you try it out real quick for us? Thanks.

**Comment by malin1993ml** [comment]
@apavlo It seems that there's some error in the script and it cannot be executed:
https://travis-ci.org/cmu-db/peloton/jobs/180169158

**Comment by SLMT** [comment]
@apavlo I just tried it. It seems like it didn't work on Fedora:

```
[slmt@fedora64 peloton]$ sh ./script/installation/packages.sh
Unknown distribution 'FEDORA
OS
REDHAT
SYSTEM
SYSTEM'
Please contact our support team for additional help. Be sure to include the contents of this message
Platform: Linux fedora64.slmt 4.5.5-300.fc24.x86_64 #1 SMP Thu May 19 13:05:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

https://github.com/cmu-db/peloton/issues
```

**Comment by apavlo** [comment]
This should fix it: https://github.com/cmu-db/peloton/pull/369/commits/a067da25c9660570cad8f1b6e98dff69b76a8cbf

**Comment by SLMT** [comment]
@apavlo It works now ! Everything looks good.

**Pull request merged**
