### PR TITLE
Interpret correctly update values

### PR DESCRIPTION
**Pull request by danielpraciano**
This PR solves bug #380 

The bug was caused by an incompatibility between the table attribute type and the update value type. The update value must be reinterpreted as the table attribute to allow correct input.

### CODE REVIEW

**Comment by apavlo** [comment]
@danielpraciano Can you rebase? I will then merge:

```bash
git remote add upstream git://github.com/cmu-db/peloton.git
git fetch upstream
git rebase -i upstream/master
git push --force
```

**Comment by PauloAmora** [comment]
@apavlo Sorry to intrude on another PR, but I did the rebase command in my PR as you say and it didn't go well, probably because the commits were already remotely pushed.

The reason I'm asking this is because @danielpraciano is our undergrad research student, and the same issues may occur.

**Comment by apavlo** [comment]
AFAIK, you have to do the rebase and not a merge. If you merge then that messes everything up.

**Comment by danielpraciano** [comment]
@apavlo I did the rebase. It seems successful.

**Pull request merged**
