### PR TITLE
Networking Team PR

### PR DESCRIPTION
**Pull request by franklinzou**
Address make error in last PR related to error function calls.

### CODE REVIEW

**Comment by nblintao** [comment]
FYI. The code review for this PR is at https://github.com/cmu-db/peloton/pull/667

**Comment by apavlo** [comment]
@franklinzou @hanli32 Has the code review comments in #667 been addressed?

**Comment by franklinzou** [comment]
@apavlo We have addressed code review comments provided by the trigger team.

**Comment by apavlo** [comment]
@nblintao Can you rebase this? Then we can merge

**Comment by nblintao** [comment]
@apavlo Oops. This is Networking team's PR. Our PR is at https://github.com/cmu-db/peloton/pull/650. I have just rebased it to reflect the latest changes in master.

**Comment by apavlo** [comment]
@nblintao Oops. Sorry about that.

@franklinzou  Can you rebase this?

**Comment by franklinzou** [comment]
@apavlo Sure, Andy. I will complete this as soon as possible.

**Comment by franklinzou** [comment]
@apavlo We have completed rebase.

**Comment by apavlo** [comment]
Change them to LOG_TRACE

**Pull request merged**
