### PR TITLE
add support for integer and decimal but it failed when adding them me…

### PR DESCRIPTION
**Pull request by mrmiywj**
Add Sqrt support for integer and decimal type.
But here are some errors.

### CODE REVIEW

**Comment by mrmiywj** [comment]
Hi, Prof.Pavlo @apavlo 
I just write a proto implementation of this feature #638. But there were some problems.

The code works, but only when one of Integer or Decimal type code added. The reason is because that the `FunctionName-FunctionData` defined [here](https://github.com/cmu-db/peloton/blob/master/src/include/catalog/catalog.h#L209) is a 1 by 1 map. Since the integer type and decimal type's sqrt function has the same name. So it will cause duplicated keys.

I have two potential solutions:
1. Change map key from `function_name` to `function_name + argument_type`.
2. Change map<Function_name, function_data> to map<Function_name, map<argument_type, function_data>. 

But I found it maybe hard to get function's argument type in `function_expression.h` when executing functions. Thus we cannot use `argument_type` as the key to find function_data.

Could you give some advice on this issue?

**Comment by mrmiywj** [comment]
BTW, this is just a prototype implement for discussion. Stuffs like tests will be added later.

**Comment by apavlo** [comment]
@mrmiywj Thanks for looking into this. See #632. We need to move all of the built-in functions (like sqrt) into the catalog. Then we can add the argument types and then do proper matching on them at runtime. If you can get this working for integers just for now, and then leave comments about what we need to do fix it later. We can merge what you have for now and then work on fixing #632 this summer.

If you are definitely coming to CMU this fall, send me an email so I know who you are.

**Comment by mrmiywj** [comment]
Implementation of sqrt function for decimal type.

Problems to fix:
On the base of current ad-hoc hack of function name to function data map, the DB does not allow two functions for two different types with same name. So we need #632 to clear the dirty hack.

**Pull request merged**
