### PR TITLE
Fix for ORDER BY (#1101)

### PR DESCRIPTION
**Pull request by poojanilangekar**
This pull request fixes the ORDER BY bug which caused the Jenkins builds to fail. The bug was in the `index_scan_executor.cpp`. The `BWTree` returned the tuples in the correct order, however we were trying to optimize the executor by consolidating all the tuples from a single physical tile into a single logical tile (thereby violating the order by clause). I have fixed the logic and it passes all the order by tests. However, I am running the code on a vagrant machine and I am not able to recreate the parallelism required to create two workers. To test if this works, @apavlo can you trigger the Jenkins build?

### CODE REVIEW

**Comment by apavlo** [comment]
@poojanilangekar Thanks!

@pervazea Were you able to recreate this bug in the LLVM engine?

**Comment by pervazea** [comment]
Yes. The bug is independent of  LLVM / codegen.


________________________________

**Comment by apavlo** [comment]
@pervazea I was stupid. I forgot that we don't support index scan in the LLVM engine yet.

@poojanilangekar Good find!

I will merge this when the build passes.

**Comment by pervazea** [comment]
1. I ran psql_test.sh on this PR on a release build, with 8 cores enabled. It passed, with the following fix:
1. Need to modify psql_test.sh according to the following diff:

-PELOTON_USER="postgres"
+PELOTON_USER="default_database"

**Pull request merged**
