### PR TITLE
Speed up compilation time

### PR DESCRIPTION
**Pull request by pmenon**
Currently, compilation time is pretty slow. The codegen component is a big culprit mainly because LLVM is a large library. But, some other reasons I've found are:

1. Include-the-world header files.
2. Heavy coupling between components.
3. Missing include-guards.

This PR is a first step at addressing these issues. The result is roughly a 15% faster build time. Not much, but on a VM it's a big step. The decoupling also means less recompilation when headers change.

There aren't any actual code changes here, mostly changing `#include` directives and forward declaring classes where appropriate.

### CODE REVIEW

**Comment by apavlo** [comment]
Thank you for splitting this from #689

**Comment by pmenon** [comment]
@pavlo this is good to go.

**Comment by apavlo** [comment]
@pmenon I missed your message. You sent it to @pavlo. Can you fix conflicts and I will merge?

**Comment by pavlo** [comment]
Hey guys, please check whether it is @pavlo or @apavlo as I am get notified from time to time. Hey Andy Pavlo, it is nice to meet you! ;-)

**Comment by pmenon** [comment]
@apavlo This is good to go.

**Comment by pmenon** [comment]
@apavlo This is can be merged in.

**Pull request merged**
