### PR TITLE
support reclaiming empty version generated by delete executor

### PR DESCRIPTION
**Pull request by yingjunwu**

### CODE REVIEW

**Comment by yingjunwu** [comment]
we still need a new delete executor logic to fundamentally reduce memory usage.

**Comment by apavlo** [comment]
> we still need a new delete executor logic to fundamentally reduce memory usage.

@yingjunwu What do you mean by this? Do we want to still merge this PR?

**Comment by yingjunwu** [comment]
@apavlo yes we still need to merge the PR. But we also need to rewrite the delete executor for avoiding empty version insertion in the future.

I will resolve the conflicts first.

**Comment by yingjunwu** [comment]
@apavlo I think this PR can be merged.

**Pull request merged**
