### PR TITLE
changes requested in #1169

### PR DESCRIPTION
**Pull request by crd477**

### CODE REVIEW

**Comment by pervazea** [comment]
The Fedora 27 debug build it failing. libasan.... which I'd guess is associated with the address sanitizer.

**Comment by pmenon** [comment]
@pervazea Looks like these sanitizer libraries, which normally come bundled with GCC, must be installed separately on Fedora/RHEL ([see here](https://bugzilla.redhat.com/show_bug.cgi?id=1303766))

@crd477 Can you modify `packages.sh` to also install `libasan`, `libubsan` and `libtasn` on Fedora/RHEL?

**Comment by crd477** [comment]
@pmenon OK, I've done this for Fedora but apparently the CentOS packages don't follow the same packaging conventions.  Even after installing ```libasan``` and ```libtsan``` there, the compiler fails with:
```
/usr/include/llvm3.9/llvm/Support/Compiler.h:389:39: fatal error: sanitizer/asan_interface.h: No suc
h file or directory
 # include <sanitizer/asan_interface.h>
                                       ^
compilation terminated.
```
In order to get those headers it seems to me like you have to install the "Software collections from the CentOS SCLo SIG" repository which then installs a new version of LLVM, clang, and all of its dependencies under ```/opt```.  Instead of messing around with this, I did the easier thing in https://github.com/cmu-db/peloton/pull/1180#commits-pushed-d49b278, which is to leave out ```-DUSE_SANITIZER=Address``` from the CentOS debug build stage (which is still commented out in any case).  If you want me to incorporate the SCLo SIG repository stuff, let me know but I'd suggest just relying on ASan results from other platforms.

@pervazea I've also commented out the unit test collection method in the Jenkinsfile that was probably wrong in the Jenkins master node case and **definitely** wrong on remote Jenkins worker VMs.  If you merge it in this state, we can see if it supports my theory about it being the cause of the executor stalls.

**Comment by pervazea** [comment]
That all the jobs for this PR are progressing on Jenkins is very encouraging.

**Pull request merged**
