### PR TITLE
Index Tuner Integration

### PR DESCRIPTION
**Pull request by jarulraj**
This PR launches index tuner when enabled like this: `./bin/peloton --index_tuner true`

TODO: Add tables, collect samples, and use constructed indexes.

### CODE REVIEW

**Comment by apavlo** [comment]
I think you need to rebase this.

**Comment by jarulraj** [comment]
Sure, rebased it. I will rebase it again after the GC PR.

**Comment by apavlo** [comment]
Not sure why the PR includes all of Ziqi's + Michael's commits?

**Comment by wangziqi2013** [comment]
Looks like a merge instead of rebase... ?

**Comment by apavlo** [comment]
Ok I merged #458 but @yingjunwu didn't rebase. Rebase this one and I'll throw it in.

**Comment by apavlo** [comment]
I'm closing this. I will make a new PR.

**Pull request closed without merging**
