### PR TITLE
Update update_test.cpp

### PR DESCRIPTION
**Pull request by Traveler98**
Changed LOG_INFO to LOG_DEBUG

### CODE REVIEW

**Comment by tli2** [comment]
Why is this relevant?

**Comment by Traveler98** [comment]
I am new to this, maybe i added this for no reason! But there was a post asking for this change. I appreciate your help if i was wrong.

**Comment by tli2** [comment]
You mean #1392

**Comment by tli2** [comment]
Okay, it doesn't make sense to apply this fix to this test case because there's another issue with it: It doesn't have any assertions in it. If you still would like to work on this issue, do you mind replacing all the print out messages with EXPECTs instead?  (A good example would be, say CreateTest)

**Pull request closed without merging**
