### PR TITLE
Peloton Consensus :: Installment #1

### PR DESCRIPTION
**Pull request by Ghatage**
Added LogCabin implementation of the RAFT consensus algorithm into Peloton.

Change Log:
==========
- Includes source for LogCabin rel 1.1.0 (https://github.com/logcabin/logcabin/releases/tag/v1.1.0)
- Changes in dependencies.py to install LogCabin in peloton/third_party
- Modified main() from LogCabin source to a minimal function to be used from within Peloton
- Included thread_manager.cpp from the nvm branch
- Builds libraft.a in peloton/third_party

Tests:
=====
- Built Peloton on a mint Ubuntu VM to make sure there are no missing deps.
- Wrote a test program which uses libraft.a and confirmed working of the cluster.

Notes:
=====
- Uses scons to build LogCabin so we aren't stuck here, will try to make it into a Makefile in future PR's.

### CODE REVIEW

**Comment by jarulraj** [comment]
I have merged it in :+1:  I renamed `Main.logcabin` to `PelotonLogCabin.cc`, and modified the Sconscript file (`../third_party/logcabin/Server/SConscript`) to compile it during scons. Refactored `dependencies.py` to avoid file renaming, and instead link the right object file.

**Comment by Ghatage** [comment]
I think [the commit](https://github.com/cmu-db/peloton/commit/2ca0e2068ca531be3850eafb0da523aa68f5c7c2) has broken the LogCabin build.
The problem is that some of the .py files and site_scons dir etc are ignored by gitignore.
It was a problem I faced too and fixed it in [this commit](https://github.com/Ghatage/peloton/commit/7bd5eb05d3ef595cf9486be8b7968e6824f2577a).
Do you want to fix it or shall I?

**Comment by jarulraj** [comment]
Let me take a shot at that.

**Comment by Ghatage** [comment]
It's the following that's missing:
peloton/third_party/logcabin-1.1.0/gtest/test/*.py
peloton/third_party/logcabin-1.1.0/gtest/xcode/Scripts/*.py
peloton/third_party/logcabin-1.1.0/gtest/scripts/*.py
peloton/third_party/logcabin-1.1.0/gtest/make/Makefile
peloton/third_party/logcabin-1.1.0/site_scons/site_tools/protoc.py
peloton/third_party/logcabin-1.1.0/scripts/*.py

**Comment by jarulraj** [comment]
Actually, send another PR with the gtest stuff that you need. Or you can disable the test Sconscript file in Logcabin.

**Comment by Ghatage** [comment]
It's resolved now, just built and confirmed. :+1:

**Pull request merged**
