### PR TITLE
Fix tpcc-fail issue

### PR DESCRIPTION
**Pull request by Michael-Tieying-Zhang**
This PR fixed the problem of #372 by removing the old version logic. This PR also fixed the issue of "unrecognized column type", which is done by @malin1993ml

### CODE REVIEW

**Comment by apavlo** [comment]
Cool. Have you tested this with OLTP-Bench?

**Comment by Michael-Tieying-Zhang** [comment]
Yes. Already tested this with OLTP-Bench.

**Comment by malin1993ml** [comment]
Can you rebase on top of master instead of merge, so that all you changes will sit on top of the merge of the last PR(18fda22206e4d30d32b05c5c72c3392e60f3e339), instead of split across that:
https://github.com/Michael-Tieying-Zhang/peloton/commits/master

Here's the guidance you could follow:
https://github.com/cmu-db/peloton/wiki/Git-survival-guide#rebase-or-how-to-screw-the-history

**Comment by Michael-Tieying-Zhang** [comment]
@malin1993ml Done.

**Pull request merged**
