### PR TITLE
Check constraints while updating a tuple

### LINKED ISSUE #938: Constraints violated on update
It looks like column constraints are not being checked on update in neither the codegen or interpreted engine.  Example session:

```
postgres=# create table test (a int, b int not null);
CREATE TABLE
postgres=# insert into test values (NULL, 1);
INSERT 0 1
postgres=# select * from test;
 a | b 
---+---
   | 1
(1 row)

postgres=# update test set b=a;
UPDATE 1
postgres=# select * from test;
 a | b 
---+---
   |  
(1 row)
```

### PR DESCRIPTION
**Pull request by seojungmin**
This PR fixes #938. It used to check the constraints only when a tuple is newly inserted. This PR also checks them at `InsertVersion()`, which is essentially called at UPDATE.

Note: After updating a tuple which violates the constraints, it produces an exception as in INSERT, however, the exception is correctly caught and the peloton instance gets **aborted**.  This is a another bug which is not related to this, but to be solved.

[SQL session]
```
postgres=# create table test (a int, b int not null);
CREATE TABLE
postgres=# insert into test values(null, 1);
INSERT 0 1
postgres=# update test set b=a;
```

[Peloton output]
```
Exception Type :: Constraint
Message :: NOTNULL constraint violated on column 'b' : FIXME
terminate called after throwing an instance of 'peloton::ConstraintException'
  what():  NOTNULL constraint violated on column 'b' : FIXME
Aborted (core dumped)
```

### CODE REVIEW

**Comment by apavlo** [comment]
@vittvolt Can you review this?

**Comment by seojungmin** [comment]
@vittvolt The API signature changes in this PR has been already done from recent other PRs. The only change is that `CheckConstraints()` is called at `InsertVersion()`.  AFAIK, `CheckConstaints()` was used to be called at `GetEmptyTuple()` initially when checking constraints is first added, and is called now in `InsertTuple()` and `InsertVersion()`. This is because, with the recent execution engine modification, `GetEmptyTuple()` is not always called with a `storage::Tuple`, but a lot of times with `nullptr`.

**Comment by seojungmin** [comment]
@vittvolt Do you have time to review this? If not, I will assign someone else. Thanks!

**Comment by vittvolt** [comment]
@seojungmin Sure no problem.

**Comment by vittvolt** [comment]
@seojungmin The abort problem after exception is probably because it's never handled. I'll open another PR for this, it was once done but never merged. I might need to ask about this in later meetings.

**Comment by seojungmin** [comment]
@vittvolt For your information, the exception handling is related to the thread pool.

**Comment by seojungmin** [comment]
@vittvolt Thanks for the review!!

**Comment by apavlo** [comment]
@seojungmin Can you rebase?

**Comment by seojungmin** [comment]
@apavlo Rebased. This should work.

**Pull request merged**
