### PR TITLE
Sending query plan between peloton nodes

### PR DESCRIPTION
**Pull request by Michael-Tieying-Zhang**
This PR mainly provide the function of sending query plan between peloton nodes. The serialization/deserialization for Postgres's nested structure takes a lot of time. The details include:

1.AbstractPlan and SeqScanPlan serialization/deserialization
2.Expression serialization/deserialization
3.Value serialization/deserialization
4.Postgres TupleDesc serialization/deserialization
5.TupleResult serialization/deserialization
6.Refacor protobuf related code
7.Refacor nested loop with IN operator
8.Unit test

### CODE REVIEW

**Comment by Michael-Tieying-Zhang** [comment]
The checks failed due to : 

04-08-2016 15:24:56 [validate_file:071] INFO : Line ::     TupleDesc tuple_desc = (TupleDesc) malloc(sizeof(struct tupleDesc));
04-08-2016 15:24:56 [<module>:109] INFO : Validation not successful

TupleDesc is a nested structure of Postgres, and it uses malloc and free to handle TupleDesc. So I also use malloc and free in order to reuse postgres's functions

**Comment by omegaga** [comment]
Don't they use palloc? It's managed by MemoryContext and thus safer to use.

**Comment by Michael-Tieying-Zhang** [comment]
Yes, they use malloc in palloc. But I didn't use palloc, due to MemoryContext problem.

**Comment by jarulraj** [comment]
@pmenon can you do a code review for the IN + SUBQUERY stuff. I think that we should handle it completely in the transformation phase and not changes the executors.

**Comment by pmenon** [comment]
Sure. Michael, this PR is conflating the RPC stuff and the subquery work.  Since this is failing to build, can you close this request and create two separate ones for the RPC work and the subquery work?

**Comment by Michael-Tieying-Zhang** [comment]
Sure

**Pull request closed without merging**
