### PR TITLE
New Parser

### PR DESCRIPTION
**Pull request by hzxa21**
This PR tears down the old parser and replaces it with the new parser based on libpg_query (resolve issue #521 ). It supports all functionalities the old parser supports and the TPC-C benchmark can successfully run on top of it. In addition, the new parser supports:

- DROP TABLE IF EXIST ...
- ORDER BY multiple expressions: `SELECT * FROM foo ORDER BY id, a+b, name DESC;`
- NULL value insertion (resolve issue #551): `insert into a values(1, NULL);` 
- Valid PRIMARY KEY DDL Syntax (resolve issue #373)

All test cases are refactored and passed except that there are memory leaks in pg_query_parse() in stats_test. We have examined this memory leaks for a while and it may because libpg is not thread_safe in our compiled version. @haojin2 @jarulraj Can you help to look into this and review this PR?

### CODE REVIEW

**Comment by hzxa21** [comment]
@haojin2 https://github.com/cmu-db/peloton/blob/master/third_party/libpg_query/src/pg_query_parse.c#L103
Why comment out this line? I guess it will cause some memory leaks without this call. Is there any particular concern?

**Comment by haojin2** [comment]
If I remember correctly, freeing the memory context will also cause the Postgres parse tree to be freed, and valgrind will then report problems on our reads from the parse tree since it is marked as freed memory if you do make the call to free memory context. I think the current postgresparsertest is not reporting any "definitely lost" kind of memory leak upon exit, but you may still see "still reachable" blocks if you run "valgrind ./test/postgresparsertest" from the build folder.

**Comment by hzxa21** [comment]
Got you. But I think we should free all the malloc memory explicitly in our codes. Even though I have done that, when we create worker thread to call the parser, the memory allocated in libpg MemoryContextCreate still leaks. That is what stats_test did. You can try and run the stats_test to see what is going on.

**Comment by haojin2** [comment]
I guess on solution to this is we can free a parsenode whenever we finish the transform of it. We may be able to alter the original version of memory context exit to let it only free the memory other than the internal parse tree.

**Comment by apavlo** [comment]
The last travis failure might be because of me. I restarted the build.

**Pull request merged**
