### PR TITLE
Fix for 'select * ' hanging

### PR DESCRIPTION
**Pull request by dengyuchenkit**
Fix for #878
The issue is due to that the server does not flush out all the packets. The client does not get the complete result so it looks like hanging.
The server should flush out all the packets before resetting the force_flush flag.

### CODE REVIEW

**Comment by seojungmin** [comment]
@dengyuchenkit This PR flushes the network packet whenever there is a `WritePackets()` call. Could you provide more information or comment about how buffering/flushing network packets work?

**Comment by hzxa21** [comment]
@dengyuchenkit Any updates for this PR?

**Comment by dengyuchenkit** [comment]
@seojungmin Oh I'm sorry. When the execution of each query is finished, the connection state will transfer to WriteState. In the write state, it calles WritePackets(https://github.com/cmu-db/peloton/blob/master/src/network/network_connection.cpp#L768). This function is mainly copying the response from the response buffer in ProtocolHandler(https://github.com/cmu-db/peloton/blob/master/src/include/network/protocol_handler.h#L51) to the buffer in NetworkConnection (packet header: https://github.com/cmu-db/peloton/blob/master/src/network/network_connection.cpp#L523. packet body: https://github.com/cmu-db/peloton/blob/master/src/network/network_connection.cpp#L552). 

But when the response size is larger than the maximum buffer size in NetworkConnection, it will flush out the content by calling FlushWriteBuffer to make room for the rest of the response. Besides, the networking layer will flush the write buffer when the force_flush flag is set to true. Usually, the force_flush flag will be set to true when the user need to get the response before sending out its next request. 

For simple query protocol (https://github.com/cmu-db/peloton/blob/master/src/network/postgres_protocol_handler.cpp#L1097), since each request needs a response, the networking layer will flush the buffer after finishing each query. For extended query protocol, there is a SYNC command by which the user requests collect the result of the previous queries (https://github.com/cmu-db/peloton/blob/master/src/network/postgres_protocol_handler.cpp#L1119). So the server will flush the result when receving a SYNC commands. User can send multiple queries between two SYNC commands. In this case, when one query is finished executing, the NetworkConnection will go to WriteState to only copy the reponse in ProtocolHandler to the local buffer. It won't flush it out until the server finally receive a SYNC or the buffer size is not enough for current response.

Currently, the result of the query execution is initially stored in the ProtocolHandler buffer as different OutputPackets. (https://github.com/cmu-db/peloton/blob/master/src/network/postgres_protocol_handler.cpp#L142). The networking layer will do an extra copy to its own byte buffer when sending it out on the network.

@hzxa21 This PR is completed but it seems it can't finish the check. I will check it.

**Comment by dengyuchenkit** [comment]
@seojungmin Previously when server calls FlushWriteBuffer(), the force_flush will be reset to false inside the function. The problem was that when there is a large response, the server will call FlushWriteBuffer() and the force_flush becomes false. Then when it comes to the last part of the response, if its size is small and the force_flush is set to false, it will not trigger the flushing. This part will not be sent out.

**Comment by dengyuchenkit** [comment]
Close this PR since there is a new one now.

**Pull request closed without merging**
