### PR TITLE
Sequential Scan + Halloween Problem Fix 

### PR DESCRIPTION
**Pull request by poojanilangekar**
This PR fixes the Halloween Problem along with the sequential scan problem.

It builds on #1240 and checks for an entry in each WriteSet for each tuple (irrespective of whether or not it updates the Primary Key). 

I have tested this with varying tile_group_count. I have also tested the fix with and without codegen. It appears to have solved the Halloween problem for both the engines.

### CODE REVIEW

**Comment by yingjunwu** [comment]
@poojanilangekar Your PR looks interesting. However, I wonder whether you could add the test case on top of my PR (or after merging my PR)? Or you could follow @pmenon's style to directly commit to my branch. Creating two PRs for a single problem usually confuses the developers, and that's what we don't want to do as discussed long time ago (1-2 years back). Sorry for the inconvenience.

**Comment by yingjunwu** [comment]
Hi @pervazea! I found that you have merged this branch to master. However, I just did a quick code review and it has bugs. The way to add statement-level write set in update executor/updater is wong. We could talk in person to discuss what's going wrong. I think you may want to revert this merge. Thank you!

**Comment by pervazea** [comment]
Reviewed this morning, prior to merging.

Will be collecting yingjunwu's comments and feedback.

**Comment by yingjunwu** [comment]
@pervazea The solution provided in this PR does not handle snapshot isolation and in-place updates. I am not sure whether you would like to revert this merge or I fix the bug in my PR?

**Pull request merged**
