### PR TITLE
Table Constraints (First Blood: Part 2 Continued)

### PR DESCRIPTION
**Pull request by vittvolt**
This is the constraint branch from https://github.com/cmu-db/peloton/pull/749

The DEFAULT crash problem has been solved (avoid using smart pointers in unit tests).

## Possible Improvements
- Delete unnecessary multi-constraint files
- Using sql queries directly in constraint tests ?
- Code optimization regarding constraint check ?
- Foreign key is still not fully functional.

### CODE REVIEW

**Comment by vittvolt** [comment]
@apavlo I'll resolve the conflicts so that it can be merged.

**Comment by vittvolt** [comment]
@apavlo I'm stuck on one last step. Merging on my local branch was fine, but I found the newly added trigger files inside the `trigger` folder are not compiled. I may need some time to figure this out.

**Comment by apavlo** [comment]
@vittvolt The source code validator failed because of a `printf`

```
[0K$ python ./script/validators/source_validator.py
09-07-2017 05:10:20 [<module>:135] INFO : Scanning : /home/travis/build/cmu-db/peloton/script/validators/../../src
09-07-2017 05:10:21 [validate_file:100] INFO : Invalid pattern --  printf\( -- found in : /home/travis/build/cmu-db/peloton/script/validators/../../src/parser/parser_utils.cpp
09-07-2017 05:10:21 [validate_file:101] INFO : Line #220 ::         printf(

09-07-2017 05:10:21 [<module>:139] INFO : Validation not successful

travis_time:end:1d184134:start=1504761020050990661,finish=1504761021193530957,duration=1142540296
[0K
[31;1mThe command "python ./script/validators/source_validator.py" exited with 255.[0m
```

Check with @haojin2 about this. I thought we removed all of these in `parser_utils.cpp`?

**Comment by haojin2** [comment]
This did not appear when I was testing my PR, I'll take a look at his parser_utils.cpp.

**Comment by haojin2** [comment]
@vittvolt Seems like you have a different version of this file in your personal repo with the one in the master, would you please rebase again?

**Comment by vittvolt** [comment]
@haojin2  Got it, thanks. But I had to disable printing the enum type in the os string, otherwise the compiler complains. https://github.com/vittvolt/peloton/blob/86fd12fc0d7dadd0006870f4c61baebd7c82391f/src/parser/parser_utils.cpp#L221

**Comment by vittvolt** [comment]
@apavlo This PR should be able to be merged by now.

**Comment by apavlo** [comment]
I have to merge by hand. Github says that there is a conflict even though there isn't. I will do this tomorrow.

**Pull request merged**
