### PR TITLE
turn on garbage collection

### PR DESCRIPTION
**Pull request by yingjunwu**
#442

### CODE REVIEW

**Comment by apavlo** [comment]
New YCSB Update Numbers:

**BEFORE**:
```
VIRT: 3736M
RES:  2275M
```

**AFTER**:
```
VIRT: 3772M
RES:  2412M
```

But if you just let the system sit idle after running the benchmark, there is one CPU spiked at 100% and the memory seems to be increasing. After letting it run for 10 minutes, the memory usage increased to 2667M.

So I think there is a problem with the GC thread.

**Comment by yingjunwu** [comment]
You mean the memory keeps increasing even if the system is idle??? It's
reasonable to observe one thread is always at 100% because it's the GC
thread and it keeps checking whether there's expired versions.

**Comment by apavlo** [comment]
Yes, the memory keeps increasing when idle. It doesn't happen when you just turn the system on without executing anything.

I don't think it's a good idea for the GC to spike the CPU at 100% if there are no txns. That looks bad. You may want to consider adding a simple counter that keeps track of the # of times that it ran but no txns were executed and then sleep for a few milliseconds.

**Comment by yingjunwu** [comment]
How do you let the system sit idle after running the benchmark? I think in
OLTP bench, the system will be closed once the benchmark finishes running.

Originally we let the gc thread to sleep periodically, but I find that in
this case the gc thread may not catch up with the execution thread under
write-intensive workload. I will tweak the gc code and let it sleep.

**Comment by apavlo** [comment]
We're not building a system just to run benchmarks. Think about if somebody was really using this. They turn on our system and it immediately spikes to 100% before they do anything. That looks bad.

Only sleep for a little bit if the last 10 times it ran it did not find anything. Then when txns start executing, it will not sleep and should be able to keep up.

Long term we are going to be able to dynamically adjust the # of threads that we use for GC.

**Comment by apavlo** [comment]
@yingjunwu As part of this, can you write some test cases for `TransactionLevelGCManager`. This code is completely untested right now.

**Comment by yingjunwu** [comment]
#447

**Comment by yingjunwu** [comment]
@apavlo you can merge this PR now.

**Comment by apavlo** [comment]
We forgot to rebase :-(

**Pull request merged**
