### PR TITLE
Add round function

### PR DESCRIPTION
**Pull request by ksaito7**
This PR adds "round" function. This implementation contains only one argument "round(numeric)". Two arguments function "round(numeric, int)" is not implemented yet.

### CODE REVIEW

**Comment by apavlo** [comment]
@ksaito7 Nice! Can you resolve the conflicts first?

**Comment by ksaito7** [comment]
@apavlo OK, but I've never resolved the conflict so far, so please give me a little time.

**Comment by pmenon** [comment]
@ksaito7 Can you fix the error and rebase?

**Comment by ksaito7** [comment]
@pmenon Sorry, I didn't recognize its existence. I will use it and update soon.

**Pull request merged**
