### PR TITLE
Refactoring index_key :)

### PR DESCRIPTION
**Pull request by wangziqi2013**
Not finished yet, please do not merge right now. I will send another notification when it is finally ready for using.

### CODE REVIEW

**Comment by apavlo** [comment]
Sup?

**Comment by malin1993ml** [comment]
Is this PR ready to go if the tests pass?

**Comment by wangziqi2013** [comment]
@malin1993ml yes, if it passes please merge it ASAP (to avoid further conflict)

 Though I hardly believe it could pass......

**Comment by malin1993ml** [comment]
@wangziqi2013 Lol... It looks good so far!

**Comment by wangziqi2013** [comment]
@malin1993ml Now it's the time!

**Comment by malin1993ml** [comment]
Done!

**Comment by wangziqi2013** [comment]
🤝

**Pull request merged**
