### PR TITLE
Fix secondary index issue: cannot find tuple after updating

### PR DESCRIPTION
**Pull request by Michael-Tieying-Zhang**
This PR fixed the secondary index issue: cannot find tuple after updating, that is described in the comment of #384 (but #384 is still there).

### CODE REVIEW

**Comment by apavlo** [comment]
I don't understand what problem this is solving? Can you make a separate issue with a more complete example?

**Comment by Michael-Tieying-Zhang** [comment]
Pls see #390

**Comment by malin1993ml** [comment]
@Michael-Tieying-Zhang The fix is good. Can you write a test case for that? You can use [SQLTestsUtil](https://github.com/cmu-db/peloton/blob/master/test/sql/sql_tests_util.cpp) to write a sql test. See how I wrote the sql test for min/max aggregation here:
https://github.com/cmu-db/peloton/tree/master/test/sql

**Comment by Michael-Tieying-Zhang** [comment]
@malin1993ml Done

**Pull request merged**
