### PR TITLE
Create hash index class

### PR DESCRIPTION
**Pull request by qwkai**
This PR creates a `HashIndex` class (mentioned in #1114) which provides a fast index to look objects based on their OIDs for the catalog team.

### CODE REVIEW

**Comment by poojanilangekar** [comment]
@qwkai, your tests are failing. Please fix them so I can review your code.

**Comment by qwkai** [comment]
Having tests failing on `ConditionalInsert`. It throws unimplemented exception because CuckooHash does not support.

**Comment by tcm-marcel** [comment]
@qwkai Are you still working on this or do you need help?

**Comment by qwkai** [comment]
@tcm-marcel I am having bugs in some tests saying that `Automatic expansion triggered when load factor was below minimum threshold`. It's a variable set in `cuckoohash_config.h`. I haven't figured out the reason leading this. Some help would be really appreciated!

**Comment by poojanilangekar** [comment]
@qwkai I know that error. It has something to do with the quality of the hash function you use. What is the hash function you are using on the key? You can try and use city hash. Also, your PR is old and is making changes which are already in the master branch. So I would suggest you pull the master and create a new branch with the relevant changes in them.

**Comment by qwkai** [comment]
Hey @poojanilangekar I am currently using CompactIntsHasher and GenericHasher on the index. I tried to include `city_hash.hh` and use CityHasher, but it seems it includes some file called `city.h` which I cannot locate. I searched codes using CityHasher but there is little useful info. Do you have any idea how to use CityHasher correctly? Thanks very much!

**Comment by poojanilangekar** [comment]
@qwkai I am looking at it. I will get back to you in a day or two.

**Comment by poojanilangekar** [comment]
@qwkai I think there is some issue with the way we compute the hash over a tuple. I changed the seed but that didn't help either. I think there is a problem with the way we combine the hashes from multiple columns. Can you try to use the `tbb::concurrent_unordered_map` and try to raise a new PR?

**Pull request closed without merging**
