### PR TITLE
Orderby/Limit Optimization

### PR DESCRIPTION
**Pull request by Michael-Tieying-Zhang**
This PR includes the optimization for order_by and limit. When the underlying plan has the same ordering with the order_by expression, order_by executor doesn't perform sort operation. Order_by executor also utilizes the limit number and offset to decrease invoking the underlying executor. Performance test has been done. It is ~1620 txns/sec on my local desk top. After the rebase with master, the throughput is ~1540 txns/sec.

### CODE REVIEW

**Comment by apavlo** [comment]
> It is ~1620 txns/sec on my local desk top. After the rebase with master, the throughput is ~1540 txns/sec.

Wait, are you saying that the throughput **decreases** with this PR?

**Comment by Michael-Tieying-Zhang** [comment]
We tested the latest version of master. It is ~1520 txns/sec. After rebase with our version (this PR), it is  ~1540/sec. It is slightly better (nearly the same) than the current master version. Before rebase, our version (already merged with last night master) is 1620 txns/sec.

**Comment by Michael-Tieying-Zhang** [comment]
Performance test is added:

Without Optimization: 
OrderBy Query (table size:100000) with Limit 10 Execution Time is: 969 ms

With Optimization: 
OrderBy Query (table size:100000) with Limit 10 Execution Time is: 320 ms
OrderBy Query (table size:100000, without limit) Execution Time is: 593 ms

**Comment by apavlo** [comment]
@Michael-Tieying-Zhang Can you fix these conflicts and I will merge?

**Comment by Michael-Tieying-Zhang** [comment]
@apavlo Done.

**Pull request merged**
