### PR TITLE
Fix bug when checking VARCHAR length

### PR DESCRIPTION
**Pull request by lixupeng**
Value::GetLength() returns the memory size of a string which is equals to strlen + 1,
While column_length records the limit of strlen.

I also reset the optimizer when Exception occurs.

### CODE REVIEW

**Comment by apavlo** [comment]
@lixupeng Does this fix #744? Can you add a test case for this issue? Check whether @PauloAmora already has one written.

**Comment by lixupeng** [comment]
@apavlo Yes, this is for #744, and another bug when ValueOutOfRangeException actually occurs. It should reset optimizer after creating Plan whether Plan is created successfully or not.

**Comment by PauloAmora** [comment]
Do I make a separate PR with the tests ?

**Comment by apavlo** [comment]
Have @lixupeng pull from your branch.

**Comment by PauloAmora** [comment]
Ok, I just uploaded it.

@lixupeng, the file can be found under the testcase_744 branch.

**Pull request merged**
