### PR TITLE
Optimizer support for predicate push-down and query-derived table

### PR DESCRIPTION
**Pull request by hzxa21**
This PR applies bug fixes for the optimizer and extends it to support predicate push-down and query-derived table.
- Single table predicates and join predicates are bound to the operators directly rather than using predicate property.
- Binder treats regular table and query derived table differently to perform correct binding.
- New logical and physical operators are added to support scan operation on query-derived tables.
- Fix a bug when enabling join commutativity rule.

Now we can support queries like:
```sql
SELECT A.c, B.c 
FROM (SELECT a+b as a, c FROM test) as A, (SELECT a+b as a, c as c from test2) as B 
WHERE A.a=B.a ORDER BY A.a
```

WIP:
- Performance test for predicate push-down and query-derived table
- Support nested queries in WHERE clause (need support for pre-connection temp table)

### CODE REVIEW

**Comment by apavlo** [comment]
> Now we can support queries like:
> ```sql
> SELECT A.c, B.c 
> FROM (SELECT a+b as a, c FROM test) as A, (SELECT a+b as a, c as c from test2) as B 
> WHERE A.a=B.a ORDER BY A.a
> ```

This is amazing! I love it!

**Comment by apavlo** [comment]
@hzxa21 @chenboy Is this PR ready to merge?

**Comment by hzxa21** [comment]
@apavlo Bowei and I are doing the framework refactoring right now. If the features supported in this PR are not critical to other teams, we think it can be merged later.

**Comment by apavlo** [comment]
Replaced with #958

**Pull request closed without merging**
