### PR TITLE
Add a setting up script for Fedora 24

### PR DESCRIPTION
**Pull request by SLMT**
I tried building Peloton on Fedora 24 and it built successfully. So I would like to provide my script for setting up necessary dependencies on Fedora 24 (64-bit).

### CODE REVIEW

**Comment by SLMT** [comment]
@sid1607 OK

**Comment by sid1607** [comment]
The postgresql-contrib package comes with the server as well and we don't want that. Have alook at this link - https://www.postgresql.org/download/linux/redhat/

I believe postgresql95 is the package that contains just the client.

**Comment by SLMT** [comment]
@sid1607 

Interesting. According to my test, installing `postgresql-contrib` on Fedora 24 (64-bit) would not install `postgresql-server` as well.

Here is the log while installing `postgresql-contrib` via `dnf`:
```
[slmt@fedora64 ~]$ sudo dnf install postgresql-contrib
Last metadata expiration check: 0:28:13 ago on Mon Nov 21 23:29:54 2016.
Dependencies resolved.
============================================================================================$
 Package                     Arch            Version                  Repository        Size
============================================================================================$
Installing:
 postgresql                  x86_64          9.5.4-1.fc24             updates          1.3 M
 postgresql-contrib          x86_64          9.5.4-1.fc24             updates          654 k
 postgresql-libs             x86_64          9.5.4-1.fc24             updates          246 k
 uuid                        x86_64          1.6.2-32.fc24            fedora            61 k

Transaction Summary
============================================================================================$
Install  4 Packages

Total download size: 2.2 M
Installed size: 7.2 M
Is this ok [y/N]: y
Downloading Packages:
(1/4): postgresql-libs-9.5.4-1.fc24.x86_64.rpm               360 kB/s | 246 kB     00:00
(2/4): uuid-1.6.2-32.fc24.x86_64.rpm                         423 kB/s |  61 kB     00:00
(3/4): postgresql-contrib-9.5.4-1.fc24.x86_64.rpm            632 kB/s | 654 kB     00:01
(4/4): postgresql-9.5.4-1.fc24.x86_64.rpm                    1.0 MB/s | 1.3 MB     00:01
---------------------------------------------------------------------------------------------
Total                                                        510 kB/s | 2.2 MB     00:04
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Installing  : postgresql-libs-9.5.4-1.fc24.x86_64                                      1/4
  Installing  : postgresql-9.5.4-1.fc24.x86_64                                           2/4
  Installing  : uuid-1.6.2-32.fc24.x86_64                                                3/4
  Installing  : postgresql-contrib-9.5.4-1.fc24.x86_64                                   4/4
  Verifying   : postgresql-contrib-9.5.4-1.fc24.x86_64                                   1/4
  Verifying   : postgresql-9.5.4-1.fc24.x86_64                                           2/4
  Verifying   : postgresql-libs-9.5.4-1.fc24.x86_64                                      3/4
  Verifying   : uuid-1.6.2-32.fc24.x86_64                                                4/4

Installed:
  postgresql.x86_64 9.5.4-1.fc24              postgresql-contrib.x86_64 9.5.4-1.fc24
  postgresql-libs.x86_64 9.5.4-1.fc24         uuid.x86_64 1.6.2-32.fc24

Complete!
```

If I check all available packages whose names start with `postgre` on `dnf`:

```
[slmt@fedora64 ~]$ dnf list postgre*
Last metadata expiration check: 0:39:45 ago on Mon Nov 21 23:27:37 2016.
Installed Packages
postgresql.x86_64                                    9.5.4-1.fc24                    @updates
postgresql-contrib.x86_64                            9.5.4-1.fc24                    @updates
postgresql-libs.x86_64                               9.5.4-1.fc24                    @updates
Available Packages
postgresql-dbi-link.noarch                           2.0.0-13.fc24                   fedora
postgresql-devel.i686                                9.5.4-1.fc24                    updates
postgresql-devel.x86_64                              9.5.4-1.fc24                    updates
postgresql-docs.x86_64                               9.5.4-1.fc24                    updates
postgresql-ip4r.x86_64                               2.0.2-9.fc24                    fedora
postgresql-jdbc.noarch                               9.4.1200-3.fc24                 fedora
postgresql-jdbc-javadoc.noarch                       9.4.1200-3.fc24                 fedora
postgresql-libs.i686                                 9.5.4-1.fc24                    updates
postgresql-odbc.x86_64                               09.05.0100-2.fc24               fedora
postgresql-odbc-tests.x86_64                         09.05.0100-2.fc24               fedora
postgresql-pgpool-II.i686                            3.5.2-1.fc24                    fedora
postgresql-pgpool-II.x86_64                          3.5.2-1.fc24                    fedora
postgresql-pgpool-II-devel.i686                      3.5.2-1.fc24                    fedora
postgresql-pgpool-II-devel.x86_64                    3.5.2-1.fc24                    fedora
postgresql-pgpool-II-extensions.x86_64               3.5.2-1.fc24                    fedora
postgresql-pgpoolAdmin.noarch                        3.4.0-3.fc24                    fedora
postgresql-plperl.x86_64                             9.5.4-1.fc24                    updates
postgresql-plpython.x86_64                           9.5.4-1.fc24                    updates
postgresql-plpython3.x86_64                          9.5.4-1.fc24                    updates
postgresql-plruby.x86_64                             0.5.4-9.fc24                    fedora
postgresql-plruby-doc.x86_64                         0.5.4-9.fc24                    fedora
postgresql-pltcl.x86_64                              9.5.4-1.fc24                    updates
postgresql-server.x86_64                             9.5.4-1.fc24                    updates
postgresql-static.i686                               9.5.4-1.fc24                    updates
postgresql-static.x86_64                             9.5.4-1.fc24                    updates
postgresql-test.x86_64                               9.5.4-1.fc24                    updates
postgresql-upgrade.x86_64                            9.5.4-1.fc24                    updates
postgresql_autodoc.noarch                            1.41-6.fc24                     fedora
postgrey.noarch                                      1.36-3.fc24                     fedora
```

It seems like `postgresql-server` available, but not installed.

I also checked if there is `postgresql`, `postgresql-server` or `postgresql95-server` service installed using `systemctl`:

```
[slmt@fedora64 ~]$ systemctl status postgresql
● postgresql.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
[slmt@fedora64 ~]$ systemctl status postgresql-server
● postgresql-server.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
[slmt@fedora64 ~]$ systemctl status postgresql95-server
● postgresql95-server.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
```

I believe that the document on the official site may have already been outdated.

**Comment by sid1607** [comment]
@SLMT Yeah, I guess it is outdated. Looks good to go!

**Comment by SLMT** [comment]
Sorry, I was wrong. The document is not outdated.

However, I believe that `postgresql-server` was not installed while installing `postgresql-contrib`. I also just found that `dnf install postgresql` is enough for PostgreSQL's clients. I will commit another version later.

Here is the log while executing `dnf install postgresql`:

```
[slmt@fedora64 ~]$ sudo dnf install postgresql
Last metadata expiration check: 0:48:16 ago on Mon Nov 21 23:29:54 2016.
Dependencies resolved.
=============================================================================================
 Package                   Arch             Version                  Repository         Size
=============================================================================================
Installing:
 postgresql                x86_64           9.5.4-1.fc24             updates           1.3 M
 postgresql-libs           x86_64           9.5.4-1.fc24             updates           246 k

Transaction Summary
=============================================================================================
Install  2 Packages

Total download size: 1.5 M
Installed size: 5.1 M
Is this ok [y/N]: y
Downloading Packages:
(1/2): postgresql-libs-9.5.4-1.fc24.x86_64.rpm               115 kB/s | 246 kB     00:02
(2/2): postgresql-9.5.4-1.fc24.x86_64.rpm                    390 kB/s | 1.3 MB     00:03
---------------------------------------------------------------------------------------------
Total                                                        353 kB/s | 1.5 MB     00:04
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Installing  : postgresql-libs-9.5.4-1.fc24.x86_64                                      1/2
  Installing  : postgresql-9.5.4-1.fc24.x86_64                                           2/2
  Verifying   : postgresql-9.5.4-1.fc24.x86_64                                           1/2
  Verifying   : postgresql-libs-9.5.4-1.fc24.x86_64                                      2/2

Installed:
  postgresql.x86_64 9.5.4-1.fc24             postgresql-libs.x86_64 9.5.4-1.fc24

Complete!
```

**Comment by sid1607** [comment]
Okay, I'll merge this PR once you make the new commit.

**Comment by SLMT** [comment]
@sid1607 

Done. Thanks for your reviews.

**Pull request merged**
