### PR TITLE
Fix for memory leak in failed CREATE transform

### PR DESCRIPTION
**Pull request by haojin2**
This PR includes the fix for memory leak issues when transformation of a CREATE statement throws an exception.

### CODE REVIEW

**Comment by seojungmin** [comment]
@haojin2 First, was there an GITHUB issue related to this, or was this something that you found that there was a leak? If it is the former case, please link the issue.

Second, is there any reason why we did not use smart pointers?

**Comment by haojin2** [comment]
One of the networking guys found this issue but did not create one on Github. I talked to one of them yesterday afternoon and started to work on this.

For the smart pointer issue, it was because the expression system does not use that. Smart pointers are good, but the migration cost is high. If I remember correctly, at the time when PostgresParser was created, we prioritized the speed of development as we wanted it to work in a short period of time thus did not have the time to migrate the whole expression system to smart pointers.

**Comment by seojungmin** [comment]
@haojin2 Thanks! I got it. 
@dengyuchenkit The code looks all right.  Can you confirm that this fix solves your problem? If it does, I think this is ready to go.

**Comment by haojin2** [comment]
It should be ready to go.

**Comment by dengyuchenkit** [comment]
Sorry, but can you hold on for a moment? I'm checking and there is still some leaks. I am checking where is that from

**Comment by dengyuchenkit** [comment]
Sorry, it's good to go! @haojin2 @seojungmin

**Comment by seojungmin** [comment]
This is ready to be merged.

**Pull request merged**
