### PR TITLE
Remove STL headers from coverage

### PR DESCRIPTION
**Pull request by pmenon**
By default, `gcov` analyzes **all** included header files, including STL, boost, and LLVM headers. This is overkill. Moreover, it's been blowing up our builds because the log file size grows beyond 4MB.

This PR adds a flag to exclude library headers when performing code coverage.

### CODE REVIEW

**Comment by apavlo** [comment]
Awesome PR. I will merge

**Comment by apavlo** [comment]
@pmenon It looks like coveralls choked on this.

**Comment by pmenon** [comment]
Hmmm, let me take a look.

**Comment by pmenon** [comment]
Looks like the `-r` doesn't because all paths are absolute.

There isn't an easy fix. I propose filtering `gcov` output for anything with "peloton" in it. It's hacky, but seems to do the job - plus, no one looks at `gcov` output in the logs directly anyways.

**Comment by apavlo** [comment]
@pmenon OK sounds reasonable

**Comment by pmenon** [comment]
@apavlo This is good to go.

**Pull request merged**
