### PR TITLE
Optimizer support for INSERT INTO SELECT

### PR DESCRIPTION
**Pull request by seojungmin**
This PR is for the Peloton's partial `INSERT INTO SELECT` support.  #136 and #700 are related issues, and the old/new optimizers have not been providing this feature.  

This PR allows the users to specify any` SELECT` queries that Peloton currently supports with `INSERT`.  However, it does not yet allow the users to specify the columns that the selected values are stored into, e.g. `INSERT INTO table_a (col_a, col_b) SELECT ...`.  Meanwhile, the user can get around this by changing the column order in `SELECT`.

This is my first go for the new optimizer, so it needs to be reviewed from one of the new optimizer authors.

### CODE REVIEW

**Comment by seojungmin** [comment]
@hzxa21 can you have a look and comment on this PR, in your spare time?  This is urgent.

**Comment by hzxa21** [comment]
Sure. I will look at this today.

**Comment by seojungmin** [comment]
@hzxa21 I commented it *wrong* last time.  I should have said that "not urgent".  I am sorry about this, and it does not have to be today.

**Comment by apavlo** [comment]
I will merge.

**Pull request merged**
