### PR TITLE
Fixing BwTree non-unique key insert problem

### PR DESCRIPTION
**Pull request by wangziqi2013**

### CODE REVIEW

**Comment by pervazea** [comment]
Changing the LOG_TRACE to LOG_DEBUG in the test output is causing the Travis debug test invocation to fail. That change in log output should not be in the PR. I assume we can find a machine on which to run with the extra logging, if this is needed to track down the issue.

**Comment by pervazea** [comment]
Reminder: revert the LOG_DEBUG back to LOG_TRACE please.

**Comment by mengranwo** [comment]
@wangziqi2013 
Hi Ziqi, can you take a look at the lin's and pervazea's comment and eliminate unnecessary log info?

**Comment by apavlo** [comment]
@wangziqi2013 We need to talk.

**Comment by wangziqi2013** [comment]
Please discard this PR. I opened a new one that should fix the problem.

**Comment by apavlo** [comment]
Replaced with #1276

**Pull request closed without merging**
