### PR TITLE
Added sql interface to load stats for the index tuner

### PR DESCRIPTION
**Pull request by MattPerron**
THIS IS A HACK. After the demo we should change this
to use the ALTER keyword instead.

The following now works from psql, I am about to test with JDBC
`load stats from 'test';`

### CODE REVIEW

**Comment by MattPerron** [comment]
I'm not sure why coveralls decreased so much, I haven't changed much

**Comment by apavlo** [comment]
Travis is being weird today because we have so much going on. I will just restart the build

**Comment by apavlo** [comment]
I think the jdbc validator is inconsistent

**Comment by MattPerron** [comment]
Did it fail again?

**Comment by apavlo** [comment]
@MattPerron Yes

**Pull request merged**
