### PR TITLE
Transaction handle

### PR DESCRIPTION
**Pull request by haoxianghua**

### CODE REVIEW

**Comment by apavlo** [comment]
Please use more descriptive commit messages. A commit message that just says "Abort" is not helpful

**Comment by pmenon** [comment]
It is difficult to see what this PR includes because the majority of changes are formatting-related. Moreover, it looks like the changes violate our formatting guidelines. 

Can you either undo the changes not related to the transaction handle, or run the [formatting script](https://github.com/cmu-db/peloton/blob/master/script/formatting/formatter.py). This will help us review the PR.

**Comment by haoxianghua** [comment]
@apavlo OK. I will add more commit.

**Comment by haoxianghua** [comment]
@pmenon OK. After I deal with the conflicting files, I will run formatting script

**Comment by apavlo** [comment]
@haoxianghua I think you should start a new branch and merge your changes manually with proper commit messages. Writing the formatter again is just going to make more changes.

**Comment by pmenon** [comment]
Redone in #733

**Pull request closed without merging**
