### PR TITLE
BwTree non-unique key insert fix

### PR DESCRIPTION
**Pull request by wangziqi2013**

### CODE REVIEW

**Comment by pmenon** [comment]
@wangziqi2013 Can you enable the unique key tests (or add new ones) in this PR as well?

**Comment by wangziqi2013** [comment]
@pmenon @pervazea Doing it now

**Comment by wangziqi2013** [comment]
@pmenon @pervazea I enabled unique key insert and delete test. The test suite is running now

**Comment by pervazea** [comment]
Jenkins is failing to check out your branch. Not clear why. Were there merge conflicts? Correctly merged with upstream master?

**Pull request merged**
